[package]
name = "organizante"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
open = "4"
clap = { version = "4.3.0", features = ["derive"] }

[dev-dependencies]
cargo-audit = "0.17.6"
